name: big_commerce_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  csv: ^5.1.1
  email_validator: ^2.1.17
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^3.0.0
  test: ^1.24.9
  json_serializable: ^6.7.1
